FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTESCODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update -y
RUN mkdir src

WORKDIR /src
COPY . /src

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

ENTRYPOINT ["streamlit", "run", "main.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.fileWatcherType=none", "--browser.gatherUsageStats=false", "--theme.base=dark"]

# docker build . -t streamlit_chatbot
# docker run -p 8501:8501 streamlit_chatbot
# ~670 MB image size


