FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTESCODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update -y
RUN mkdir src

WORKDIR /src
COPY . /src

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

ENTRYPOINT ["/bin/bash"]

CMD ["streamlit", "run", "main.py", "--server.fileWatcherType", "none", "--browser.gatherUsageStats", "false", "--theme.base", "dark"]